// table schema generated by introspection
import {
  mysqlTable,
  unique,
  varchar,
  int,
  timestamp,
  text,
  boolean
} from 'drizzle-orm/mysql-core';

export type User = {
  id: string;
  name: string;
  age: number;
  email: string;
  description: string;
  is_active: boolean;
  created_at: Date;
  updated_at: Date;
};

export const usersTable = mysqlTable(
  'users',
  {
    id: varchar('id', { length: 36 }).primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
    name: varchar('name', { length: 255 }).notNull(),
    age: int('age').notNull(),
    email: varchar('email', { length: 255 }).notNull(),
    description: text('description'),
    is_active: boolean('is_active').notNull().default(true),
    created_at: timestamp('created_at').notNull().defaultNow(),
    updated_at: timestamp('updated_at').notNull().defaultNow(),
  },
  (table) => [
    unique('users_id').on(table.id),
    unique('users_email_unique').on(table.email),
  ],
);
